### ISSUE TITLE
Data request

### ISSUE THREAD

**Issue by sumant-28** [jwelch1123/amazon_scrape#1]
Hello. I saw your blog post about scraping audible https://nycdatascience.com/blog/student-works/the-library-of-audible-web-scraping/ which is something I have been thinking about. The data I was looking for was audiobooks (specifically non fiction) read by the narrator. Since you already did the work can I have a copy of the data if you have it? Otherwise I can get my hands dirty and maybe fork this

**Comment by jwelch1123** [comment]
Hello, 

This is actually the wrong repo for that project, this repo is to preserve the Amazon scraping code before I abandoned that part of the project but the Audible scraping code exists just in a [different repo](https://github.com/jwelch1123/finding_the_tree_in_the_forest).

Here is a [link for download](https://www.dropbox.com/sh/f707g1w670icuyn/AAC-SOPmZrclAlTTKnZ37YrAa?dl=0) I will leave it open a few days. You will need some fuzzy string matching to match the authors to narrators and the fiction-nonfiction distinction is a little messy in this data set. Best of luck

**Comment by sumant-28** [comment]
Thank you. Yes I have now cleaned the data so that it is in a state where I can use it for my purposes.

Sumant
________________________________
